### ISSUE TITLE
При падении Redis ложится сайт!

### ISSUE THREAD

**Issue by Valeriyy** [DimMount/dimmount.rediscache#1]
Офигенный модуль, кладём redis и получаем:
`RedisException] 
Redis server went away (0)
/home/www/htdocs/bitrix/modules/dimmount.rediscache/include.php:54
#0: Redis->ping()
	/home/www/htdocs/bitrix/modules/dimmount.rediscache/include.php:54
#1: CPHPCacheRedis->CPHPCacheRedis()
	/home/www/htdocs/bitrix/modules/dimmount.rediscache/include.php:37
#2: CPHPCacheRedis->__construct()
	/home/www/htdocs/bitrix/modules/main/lib/data/cache.php:81
#3: Bitrix\Main\Data\Cache::createCacheEngine()
	/home/www/htdocs/bitrix/modules/main/lib/data/cache.php:141
#4: Bitrix\Main\Data\Cache::createInstance()
	/home/www/htdocs/bitrix/modules/main/lib/data/managedcache.php:49
#5: Bitrix\Main\Data\ManagedCache->read(integer, string)
	/home/www/htdocs/bitrix/modules/main/lib/config/option.php:173
#6: Bitrix\Main\Config\Option::load(string, NULL)
	/home/www/htdocs/bitrix/modules/main/lib/config/option.php:53
#7: Bitrix\Main\Config\Option::get(string, string, string)
	/home/www/htdocs/bitrix/modules/main/lib/httprequest.php:337
#8: Bitrix\Main\HttpRequest->prepareCookie(array)
	/home/www/htdocs/bitrix/modules/main/lib/httprequest.php:63
#9: Bitrix\Main\HttpRequest->__construct(object, array, array, array, array)
	/home/www/htdocs/bitrix/modules/main/lib/httpapplication.php:43
#10: Bitrix\Main\HttpApplication->initializeContext(array)
	/home/www/htdocs/bitrix/modules/main/lib/application.php:122
#11: Bitrix\Main\Application->initializeExtendedKernel(array)
	/home/www/htdocs/bitrix/modules/main/include.php:24
#12: require_once(string)
	/home/www/htdocs/bitrix/modules/main/include/prolog_before.php:14
#13: require_once(string)
	/home/www/htdocs/bitrix/modules/main/include/prolog.php:10
#14: require_once(string)
	/home/www/htdocs/bitrix/header.php:1
#15: require(string)
	/home/www/htdocs/index.php:14`

**Comment by DimMount** [comment]
Исправлено
