### ISSUE TITLE
Could not start session by PHP

### ISSUE THREAD

**Issue by alxbychkov** [DimMount/dimmount.rediscache#3]
Сделал все по инструкции. redis установлен. Может я что то упустил. Сайт в итоге не открывается.

**Comment by DimMount** [comment]
не похоже, что эта ошибка связана с редисом.
такая ошибка происходит при старте сессии https://doc.budagov.ru/class_bitrix_1_1_main_1_1_session_1_1_session.html#af8fa59992209e36dccb3eefb0f75531f
в данном модуле сессии не используются

**Comment by alxbychkov** [comment]
Да, ты прав. Я не￼ могу запуститься если меняю session.save_handler на redis, в php.ini. Если оставить files по умолчанию, то ошибки не возникает. В админке показывает что используется cphpcacheredis. Значит все работает? Не могу сообразить как это проверить.

**Comment by DimMount** [comment]
запустить `redis-cli`
в нем запустить команду `MONITORING`

и смотреть запросы к редису в момент просмотра страниц

**Comment by alxbychkov** [comment]
Спасибо, попробовал. Движуха в консоли идет. Буду тестировать.
